### ISSUE TITLE
Files to copy is missing Rakefile

### ISSUE THREAD

**Issue by segiddins** [fastlane/monorepo#13]
https://github.com/fastlane/monorepo/blob/master/files_to_copy/.travis.yml#L9 refers to Rake, but `rake` isn't in the `Gemfile` nor is there a Rakefile

**Comment by KrauseFx** [comment]
Very good point, thanks. The files from `files_to_copy` will actually be copied over in the same folder as the [countdown repo](https://github.com/fastlane/countdown).
I'll add `rake` to the `Gemfile` :+1:
